### ISSUE TITLE
dependency

### ISSUE THREAD

**Issue by Gasimzade09** [rbkmoney/three-ds-server-storage#29]
Hi everybody,
I cloned this project but can not to run it, because I can not find this dependency:
<dependency>
            <groupId>com.rbkmoney</groupId>
            <artifactId>schedulator-proto</artifactId>
            <version>1.11-efc08c2</version>
        </dependency>
please help!

**Comment by antonlva** [comment]
Hi,

I've opensourced shedulator proto https://github.com/rbkmoney/schedulator-proto, you can try running build again. 
Also plz take a look at https://github.com/rbkmoney/three-ds-server-compose - it can help to run all the 3DSS software automatically.

**Comment by Gasimzade09** [comment]
I am trying to generate java code from schedule.thrift 
what i get in console:

[WARNING:G:/schedulator/schedulator-proto/proto/schedule.thrift:1] Could not find include file base.thrift

[WARNING:G:/schedulator/schedulator-proto/proto/schedule.thrift:2] Could not find include file domain.thrift

[WARNING:G:/schedulator/schedulator-proto/proto/schedule.thrift:3] Could not find include file payout_processing.thrift

[WARNING:G:/schedulator/schedulator-proto/proto/schedule.thrift:8] No generator named 'erlang' could be found!
